### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by FreeGoldRush** [evyatarmeged/Humanoid#6]
Installed.  Trying to run your example with my own url:

#!/usr/bin/env nodejs

const Humanoid = require("humanoid-js");

let humanoid = new Humanoid();
humanoid.get("https://www.psacard.com/cert/47002793")
    .then(res => {
        console.log(res.body) // <!DOCTYPE html><html lang="en">...
        console.log(res.isChallengeSolved);
        humanoid.bypassJSChallenge(res);
    })
    .catch(err => {
        console.error(err)
    })

Response is the challenge page plus the text below.  I do not get the protected page.  Any ideas?

false
(node:13573) UnhandledPromiseRejectionWarning: Error: Could not solve or parse JavaScript challenge. Caused due to error:
TypeError: Cannot read property 'length' of null
    at Function.solveChallenge (/home/ubuntu/node_modules/humanoid-js/src/solver.js:89:10)
    at Humanoid.bypassJSChallenge (/home/ubuntu/node_modules/humanoid-js/index.js:71:30)
    at /home/ubuntu/test.js:10:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13573) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13573) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by RisedSky** [comment]
hello, have you made it work finally ? or do you have the same pb?

**Comment by FreeGoldRush** [comment]
> hello, have you made it work finally ? or do you have the same pb?

This was 2.5 years ago. Gave up on it long ago.
